### ISSUE TITLE
Unexpected validation on save

### ISSUE THREAD

**Issue by lzl124631x** [blakehaswell/mongoose-unique-validator#110]
```
// mongo 3 does't support validation when update. So instead of findOneAndUpdate, use findOne + save.
UserInfo.findOne({ userId: userInfo.userId })
    .then((ui) => {
        ui = Object.assign(ui, userInfo);
        return ui.save();
    })
```

I'm using the above code to do update with validation. Without this plugin it works fine. But if I add this plugin, it failed with errors about all the unque fields, including `_id`.

Is this expected? Any workaround? Thanks

**Comment by m-weeks** [comment]
If you trying doing `ui.set(userInfo)` instead of `Object.assign` does it still fail?

**Comment by lzl124631x** [comment]
```
UserInfo.findOne({ userId: userInfo.userId })
    .then((ui) => {
        ui.set(userInfo);
        return ui.save();
    })
```

It still fail with `ui.set(userInfo)`... Same error. Even the `_id` of the userInfo doesn't change. I don't this is expected?

**Comment by lzl124631x** [comment]
I ended up with using `findOneAndUpdate` + `{ runValidators: true, context: 'query' }` which is mentioned in the README. Thanks for the help!

**Comment by eskiimo** [comment]
mongoose-unique-validator has a bug in it so that when you have multiple users it detects the reference to _id in another schema. Then it decides that _id is no longer unique and will not let any user post a new Document.

The fix at the moment is to re-roll mongoose and mongoose-unique-validator to v^5.11.13 and v^2.0.3 respectively.

There is a current GitHub issue posted here.

https://github.com/blakehaswell/mongoose-unique-validator/issues/131

Answered By – [James Beswick](https://stackoverflow.com/questions/69618716/mongodb-atlas-and-mongoose-unique-id-not-registering-as-unique/69619661#69619661)
