### ISSUE TITLE
2.0.2 version downloads the 2.0.4 version code

### ISSUE THREAD

**Issue by bipinstha7** [blakehaswell/mongoose-unique-validator#130]
Hi there,
Our prod has a 2.0.2 version. 

According to GitHub, 2 days ago this package version was changed to 2.0.4 with some changes and package.json packages update. 

The new codes should only be available to 2.0.4 right? but we also got it on 2.0.2 which broke our app. Mongoose version 6.0.0 on your side broke everything. This is how you manage your package? Did we miss something or have some problem on our side? 

Could you please let me know how 2.0.2 got the codes of 2.0.4? Thank you

**Comment by viveleroi** [comment]
> Could you please let me know how 2.0.2 got the codes of 2.0.4? Thank you

First of all, you're right I should have versioned a major dep jump different. It's been over two years since I've done this and everyone needed me to jump in. I'll rework this today.

However, sounds like you're not actually locked to v2.0.2, but a range. You should really understand how version ranges work. If you're asking this, you're making things harder on yourself because when things break, you don't understand how NPM is giving you what it is.

**Comment by bipinstha7** [comment]
@viveleroi, Thank you for the response. 

Yea, I'm a bit confused here with versioning and maybe I am wrong but if something breaks, it should be on the major version right? Personally, I haven't worked with any NPM packages so I don't understand much how NPM is providing the versions. As much as I know if something breaks, it should be on the major version.

And thank you for your work for the community. :)

**Comment by bipinstha7** [comment]
@viveleroi, It seems you have fixed it with the major version **3.0.0**.

Thank you
