### ISSUE TITLE
Provide a changelog and optimally follow semver :)

### ISSUE THREAD

**Issue by timbru31** [blakehaswell/mongoose-unique-validator#40]
Hey there,

more sort of a meta issue.
I've noticed the major version bump form 0.6.2 to 1.0.0 and automatically assumed a major (and breaking) change.
I've looked around for a changelog, but was unable to find a document or a release documentation in the release tab. Would you mind to have e.g. a CHANGELOG.md in the repo?
Makes updating a lot easier if breaking changes would be listed there :)

Additionally the [semver](http://semver.org/) concept allows your users to immediately notice any breaking changes or just bug fixes - take a look at it and if you want use it in the future.

Thanks again for maintaining this project!

**Comment by viveleroi** [comment]
Thanks, I'm familiar with semver and try to always adhere to it, but making the jump without having any api breakage was inevitable. Previous versioning was stuck in "pre-1.0" yet the product has been stable for some time now, and there's no intention of making any breaking changes. A better time to handle the change probably was when I took this project over, with a `-beta` or something due to the major internal rewrite but that was six months ago.

The changelog is something I can start maintaining.
